image: maven:latest

build:
  stage: build
  tags:
    - docker-runner
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  tags:
    - docker-runner
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  tags:
    - docker-runner
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master