before_script:    
    - export MAVEN_HOME=/usr/local/apache-maven
    - export JAVA_HOME=/usr/local/jdk1.8.0_201
build:
    script:
    - 'pwd && $MAVEN_HOME/bin/mvn test'
    tags:  
    - common-runner